export const cards = [
  { title: 'Dog 1', contact: 'person1@email.com', likes: 0 },
  { title: 'Dog 2', contact: 'person2@email.com', likes: 0 },
  { title: 'Dog 3', contact: 'person3@email.com', likes: 0 },
  { title: 'Dog 4', contact: 'person4@email.com', likes: 0 },
  { title: 'Dog 5', contact: 'person5@email.com', likes: 0 },
  { title: 'Dog 6', contact: 'person6@email.com', likes: 0 },
  { title: 'Dog 7', contact: 'person7@email.com', likes: 0 },
  { title: 'Dog 8', contact: 'person8@email.com', likes: 0 },
  { title: 'Dog 9', contact: 'person9@email.com', likes: 0 },
  { title: 'Dog 10', contact: 'person10@email.com', likes: 0 },
  { title: 'Dog 11', contact: 'person11@email.com', likes: 0 },
  { title: 'Dog 12', contact: 'person12@email.com', likes: 0 },
  { title: 'Dog 13', contact: 'person13@email.com', likes: 0 },
  { title: 'Dog 14', contact: 'person14@email.com', likes: 0 },
  { title: 'Dog 15', contact: 'person15@email.com', likes: 0 },
  { title: 'Dog 16', contact: 'person16@email.com', likes: 0 },
];
